/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesBajas;

import cjb.ci.CtrlInterfaz;
import codigo.MnpHDEP;
import codigo.NodoML;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristo
 */
public class VntBajaPaciente extends javax.swing.JFrame
{

    /**
     * Creates new form VntBajaEspecialidad
     */
    public VntBajaPaciente()
    {
        initComponents();
        try
        {
            jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
            jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(jcDependencia.getSelectedItem().toString())));
            jcEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarEspecialidadesCmbox(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString())));
            jcPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarPacientesCmbox(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString(), jcEspecialidad.getSelectedItem().toString())));

            jcDependencia.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    String dependenciaSeleccionada = jcDependencia.getSelectedItem().toString();
                    jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(
                            codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(dependenciaSeleccionada)
                    ));
                    jcEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarEspecialidadesCmbox(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString())));
                    jcPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarPacientesCmbox(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString(), jcEspecialidad.getSelectedItem().toString())));
                }
            });

            jcHospital.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    String dependenciaSeleccionada = jcDependencia.getSelectedItem().toString();
                    String hpSeleccionado = jcHospital.getSelectedItem().toString();
                    jcEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(
                            codigo.MnpHDEP.mostrarEspecialidadesCmbox(dependenciaSeleccionada, hpSeleccionado)
                    ));
                    jcPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarPacientesCmbox(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString(), jcEspecialidad.getSelectedItem().toString())));
                }
            });

            jcEspecialidad.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    String dependenciaSeleccionada = jcDependencia.getSelectedItem().toString();
                    String hpSeleccionado = jcHospital.getSelectedItem().toString();
                    String ep = jcEspecialidad.getSelectedItem().toString();
                    jcPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(
                            codigo.MnpHDEP.mostrarPacientesCmbox(dependenciaSeleccionada, hpSeleccionado, ep)
                    ));
                }
            });
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error inesperado", "Error ", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jcDependencia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcHospital = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jcEspecialidad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcPaciente = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja paciente");
        setType(java.awt.Window.Type.UTILITY);
        addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                formKeyPressed(evt);
            }
        });

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDependencia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcDependenciaKeyPressed(evt);
            }
        });

        jLabel1.setText("Selecciona la dependencia a la que pertenece la especialidad que quieres dar de baja");

        jLabel2.setText("Selecciona el hospital a la que pertenece el paciente que deseas dar de baja");

        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcHospital.setEnabled(false);
        jcHospital.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcHospitalKeyPressed(evt);
            }
        });

        jLabel3.setText("Selecciona la especialidad a la que pertenece el paciente que quieres dar de baja");

        jcEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcEspecialidad.setEnabled(false);
        jcEspecialidad.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcEspecialidadKeyPressed(evt);
            }
        });

        jLabel4.setText("Selecciona el paciente que deseas dar de baja");

        jcPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcPaciente.setEnabled(false);
        jcPaciente.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcPacienteKeyPressed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jcEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jcPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jcEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jcPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAceptar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed

        if (jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas") || jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados") || jcEspecialidad.getSelectedItem().toString().equals("Sin especialidades registradas") || jcPaciente.getSelectedItem().toString().equals("Sin pacientes registrados"))
        {
            JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio para poder llevar a cabo esta acción", "Campos invalidos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dependencia = jcDependencia.getSelectedItem().toString();
        String hospital = jcHospital.getSelectedItem().toString();
        String especialidad = jcEspecialidad.getSelectedItem().toString();
        String paciente = jcPaciente.getSelectedItem().toString();

        
        
        NodoML aux = MnpHDEP.verificarTemporales(dependencia, hospital);
        if (aux != null)
        {
            hospital = aux.getEtiqueta();
            MnpHDEP.bajaPaciente(dependencia, hospital, especialidad, paciente);
            JOptionPane.showMessageDialog(this, "HOSPITAL EN REMODELACIÓN, CAMBIOS HECHOS EN HOSPITAL TEMPORAL: " + aux.getEtiqueta() + "\n" + "El paciente: " + paciente + " fue dado de baja correctamente", "Baja paciente", JOptionPane.INFORMATION_MESSAGE);
        } else
        {
            MnpHDEP.bajaPaciente(dependencia, hospital, especialidad, paciente);
            JOptionPane.showMessageDialog(this, "El paciente: " + paciente + " fue dado de baja correctamente", "Baja paciente", JOptionPane.INFORMATION_MESSAGE);
        }

        CtrlInterfaz.habilita(false, jcHospital, jcEspecialidad, jcPaciente, btnAceptar);
        CtrlInterfaz.cambia(jcDependencia);

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(jcDependencia.getSelectedItem().toString())));
        jcEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarEspecialidadesCmbox(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString())));
        jcPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarPacientesCmbox(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString(), jcEspecialidad.getSelectedItem().toString())));
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed
    {//GEN-HEADEREND:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jcDependenciaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcDependenciaKeyPressed
    {//GEN-HEADEREND:event_jcDependenciaKeyPressed
        if (evt.getKeyChar() == '\n' && jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas"))
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jcHospital.setEnabled(true);
            jcHospital.requestFocus();
        }
    }//GEN-LAST:event_jcDependenciaKeyPressed

    private void jcHospitalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcHospitalKeyPressed
    {//GEN-HEADEREND:event_jcHospitalKeyPressed
        if (jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados") && evt.getKeyChar() == '\n')
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jcEspecialidad.setEnabled(true);
            jcEspecialidad.requestFocus();
        }
    }//GEN-LAST:event_jcHospitalKeyPressed

    private void jcEspecialidadKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcEspecialidadKeyPressed
    {//GEN-HEADEREND:event_jcEspecialidadKeyPressed
        if (evt.getKeyChar() == '\n' && jcEspecialidad.getSelectedItem().toString().equals("Sin especialidades registradas"))
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jcPaciente.setEnabled(true);
            jcPaciente.requestFocus();
        }
    }//GEN-LAST:event_jcEspecialidadKeyPressed

    private void jcPacienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcPacienteKeyPressed
    {//GEN-HEADEREND:event_jcPacienteKeyPressed
        if (evt.getKeyChar() == '\n' && jcPaciente.getSelectedItem().toString().equals("Sin pacientes registrados"))
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            btnAceptar.setEnabled(true);
            btnAceptar.requestFocus();
        }
    }//GEN-LAST:event_jcPacienteKeyPressed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VntBajaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jcDependencia;
    private javax.swing.JComboBox<String> jcEspecialidad;
    private javax.swing.JComboBox<String> jcHospital;
    private javax.swing.JComboBox<String> jcPaciente;
    // End of variables declaration//GEN-END:variables
}
