/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesBajas;

import cjb.ci.CtrlInterfaz;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristo
 */
public class VntBajaDependencia extends javax.swing.JFrame
{

    /**
     * Creates new form VntBajaDependencia
     */
    public VntBajaDependencia()
    {
        initComponents();
        try
        {
            jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error inesperado", "Error ", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jcDependencia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja dependencia");
        setType(java.awt.Window.Type.UTILITY);

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDependencia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcDependenciaKeyPressed(evt);
            }
        });

        jLabel1.setText("Selecciona la dependencia que deseas dar de baja");

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAceptar)
                            .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(289, 289, 289))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnAceptar)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed

        if (jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas"))
        {
            JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio para poder llevar a cabo esta acción", "Campos invalidos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dependencia = jcDependencia.getSelectedItem().toString();
        codigo.MnpHDEP.bajaDependencia(dependencia);
        JOptionPane.showMessageDialog(this, "La dependencia: " + dependencia + " fue dada de baja correctamente", "Baja dependencia", JOptionPane.INFORMATION_MESSAGE);

        CtrlInterfaz.habilita(false, btnAceptar);
        CtrlInterfaz.cambia(jcDependencia);
        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jcDependenciaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcDependenciaKeyPressed
    {//GEN-HEADEREND:event_jcDependenciaKeyPressed
        if (evt.getKeyChar() == '\n' && jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas"))
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            btnAceptar.setEnabled(true);
            btnAceptar.requestFocus();
        }
    }//GEN-LAST:event_jcDependenciaKeyPressed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VntBajaDependencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VntBajaDependencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcDependencia;
    // End of variables declaration//GEN-END:variables
}
