/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesAltas;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import codigo.Especialidad;
import codigo.Hospital;
import codigo.MnpHDEP;
import codigo.NodoML;
import javax.swing.JOptionPane;

/**
 *
 * @author ErIcK
 */
public class VntAltaEspecialidad extends javax.swing.JFrame
{

    /**
     * Creates new form VntAltaDependencia
     */
    public VntAltaEspecialidad()
    {
        initComponents();
        try
        {
            jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
            jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(jcDependencia.getSelectedItem().toString())));

            jcDependencia.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    String dependenciaSeleccionada = jcDependencia.getSelectedItem().toString();
                    jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(
                            codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(dependenciaSeleccionada)
                    ));
                }
            });
        } catch (Exception e)
        {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtNoMedicos = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtNoCamas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcDependencia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jcHospital = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta especialidad");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Ingresa el nombre de la especialidad:");

        jLabel2.setText("Ingresa el número de medicos");

        jtNombre.setEnabled(false);
        jtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtNombreKeyTyped(evt);
            }
        });

        jtNoMedicos.setEnabled(false);
        jtNoMedicos.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtNoMedicosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtNoMedicosKeyTyped(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });

        jLabel3.setText("Ingresa el número de camas");

        jtNoCamas.setEnabled(false);
        jtNoCamas.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtNoCamasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtNoCamasKeyTyped(evt);
            }
        });

        jLabel4.setText("Selecciona la dependencia a la que pertenece la especialidad");

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDependencia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcDependenciaKeyPressed(evt);
            }
        });

        jLabel5.setText("Selecciona el hospital al que pertenece la especialidad");

        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcHospital.setEnabled(false);
        jcHospital.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcHospitalKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(141, 141, 141)
                                        .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNoMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNoCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtNoMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addComponent(jtNoCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed

        if (jtNombre.getText().trim().length() == 0 || jtNoMedicos.getText().length() == 0 || jtNoCamas.getText().length() == 0 || jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas") || jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados"))
        {
            JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio para poder llevar a cabo esta acción", "Alta Especialidad", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (MnpHDEP.verificarNoDuplicadosDeEspecialidad(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString(), jtNombre.getText().toLowerCase().trim()))
        {

            JOptionPane.showMessageDialog(this, "No puedes ingresar una especialidad con el mismo nombre en este hospital ", "Dato no valido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombre = jtNombre.getText().toLowerCase().trim();
        int noCamas = Integer.parseInt(jtNoCamas.getText());
        int noMedicos = Integer.parseInt(jtNoMedicos.getText());
        String dependencia = jcDependencia.getSelectedItem().toString();
        String hospital = jcHospital.getSelectedItem().toString();

        NodoML<Hospital> n = MnpHDEP.encontrarHospital(dependencia, hospital);
        NodoML<Hospital> tm = MnpHDEP.verificarTemporales(dependencia, hospital);

        if (tm != null)
        {
            if (tm.getObj().getNivel() != 3 && (nombre.equals("oncología") || nombre.equals("oncologia") || nombre.equals("neurocirugia") || nombre.equals("neurocirugía")))
            {
                JOptionPane.showMessageDialog(this, "La especialidad: " + nombre + " no puede ser dada de alta a menos que subas el hospital a tercer nivel ", "Alta especialidad", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (tm.getObj().getNivel() == 3 && (nombre.equals("oncología") || nombre.equals("oncologia") || nombre.equals("neurocirugia") || nombre.equals("neurocirugía")))
            {
                JOptionPane.showMessageDialog(this, "La especialidad: " + nombre + " no puede ser dada de alta porque ya tienes una existente ", "Alta especialidad", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }else if (n != null)
        {

            if (n.getObj().getNivel() != 3 && (nombre.equals("oncología") || nombre.equals("oncologia") || nombre.equals("neurocirugia") || nombre.equals("neurocirugía")))
            {
                JOptionPane.showMessageDialog(this, "La especialidad: " + nombre + " no puede ser dada de alta a menos que subas el hospital a tercer nivel ", "Alta especialidad", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (n.getObj().getNivel() == 3 && (nombre.equals("oncología") || nombre.equals("oncologia") || nombre.equals("neurocirugia") || nombre.equals("neurocirugía")))
            {
                JOptionPane.showMessageDialog(this, "La especialidad: " + nombre + " no puede ser dada de alta porque ya tienes una existente ", "Alta especialidad", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        nombre = jtNombre.getText().trim();
        
//        NodoML aux = MnpHDEP.verificarTemporales(dependencia, hospital);

        if (tm != null)
        {
            codigo.MnpHDEP.altaEspecialidad(nombre, noCamas, noMedicos, dependencia, tm.getObj().getNombre());
            JOptionPane.showMessageDialog(this, "HOSPITAL EN REMODELACIÓN, CAMBIOS HECHOS EN HOSPITAL TEMPORAL: " + tm.getEtiqueta() + "\n" + "La especialidad " + nombre + " fue dada de alta correctamente", "Alta especialidad", JOptionPane.INFORMATION_MESSAGE);
        } else if( n != null)
        {
            codigo.MnpHDEP.altaEspecialidad(nombre, noCamas, noMedicos, dependencia, hospital);
            JOptionPane.showMessageDialog(this, "La especialidad " + nombre + " fue dada de alta correctamente", "Alta especialidad", JOptionPane.INFORMATION_MESSAGE);
        }

        CtrlInterfaz.limpia(jtNombre, jtNoMedicos, jtNoCamas);
        CtrlInterfaz.habilita(false, jtNoMedicos, jtNoCamas, btnAceptar, jcHospital, jtNombre);
        //validacion
        CtrlInterfaz.cambia(jcDependencia);

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(jcDependencia.getSelectedItem().toString())));
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNombreKeyPressed
    {//GEN-HEADEREND:event_jtNombreKeyPressed
        String nombre = jtNombre.getText().toLowerCase().trim();
        String dependencia = jcDependencia.getSelectedItem().toString();
        String hospital = jcHospital.getSelectedItem().toString();
        NodoML<Hospital> n = MnpHDEP.encontrarHospital(dependencia, hospital);
        if (n != null)
        {

            if (n.getObj().getNivel() != 3 && (nombre.equals("oncología") || nombre.equals("oncologia") || nombre.equals("neurocirugia") || nombre.equals("neurocirugía")))
            {
                JOptionPane.showMessageDialog(this, "La especialidad: " + nombre + " no puede ser dada de alta a menos que subas el hospital a tercer nivel ", "Alta especialidad", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (n.getObj().getNivel() == 3 && (nombre.equals("oncología") || nombre.equals("oncologia") || nombre.equals("neurocirugia") || nombre.equals("neurocirugía")))
            {
                JOptionPane.showMessageDialog(this, "La especialidad: " + nombre + " no puede ser dada de alta porque ya tienes una existente ", "Alta especialidad", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        if (evt.getKeyChar() == '\n' && MnpHDEP.verificarNoDuplicadosDeEspecialidad(jcDependencia.getSelectedItem().toString(), jcHospital.getSelectedItem().toString(), jtNombre.getText().toLowerCase().trim()))
        {

            JOptionPane.showMessageDialog(this, "No puedes ingresar una especialidad con el mismo nombre en este hospital ", "Dato no valido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Validaciones.enterCadenaNoVacia(this, evt, jtNombre, jtNoMedicos);
    }//GEN-LAST:event_jtNombreKeyPressed

    private void jtNoMedicosKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNoMedicosKeyPressed
    {//GEN-HEADEREND:event_jtNoMedicosKeyPressed
        Validaciones.enterEntero(this, evt, jtNoMedicos, jtNoCamas);
    }//GEN-LAST:event_jtNoMedicosKeyPressed

    private void jtNoCamasKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNoCamasKeyPressed
    {//GEN-HEADEREND:event_jtNoCamasKeyPressed
//        if (evt.getKeyChar() == '\n' && jtNoCamas.getText().length() == 0)
//        {
//            JOptionPane.showMessageDialog(this, "Ingresa un número para poder pasar a la siguiente acción ", "Acción no permitida", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
        Validaciones.enterEntero(this, evt, jtNoCamas, btnAceptar);
    }//GEN-LAST:event_jtNoCamasKeyPressed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    private void jcDependenciaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcDependenciaKeyPressed
    {//GEN-HEADEREND:event_jcDependenciaKeyPressed
        if (evt.getKeyChar() == '\n' && jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas"))
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jcHospital.setEnabled(true);
            jcHospital.requestFocus();
        }
    }//GEN-LAST:event_jcDependenciaKeyPressed

    private void jcHospitalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcHospitalKeyPressed
    {//GEN-HEADEREND:event_jcHospitalKeyPressed
        if (jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados") && evt.getKeyChar() == '\n')
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jtNombre.setEnabled(true);
            jtNombre.requestFocus();
        }
    }//GEN-LAST:event_jcHospitalKeyPressed

    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNombreKeyTyped
    {//GEN-HEADEREND:event_jtNombreKeyTyped
        Validaciones.validaAlfabeticos(evt, 20, jtNombre.getText());
    }//GEN-LAST:event_jtNombreKeyTyped

    private void jtNoMedicosKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNoMedicosKeyTyped
    {//GEN-HEADEREND:event_jtNoMedicosKeyTyped
        Validaciones.validaEntero(evt, 2, jtNoMedicos.getText());
    }//GEN-LAST:event_jtNoMedicosKeyTyped

    private void jtNoCamasKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNoCamasKeyTyped
    {//GEN-HEADEREND:event_jtNoCamasKeyTyped
        Validaciones.validaEntero(evt, 2, jtNoCamas.getText());
    }//GEN-LAST:event_jtNoCamasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VntAltaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VntAltaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VntAltaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VntAltaEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VntAltaEspecialidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcDependencia;
    private javax.swing.JComboBox<String> jcHospital;
    private javax.swing.JTextField jtNoCamas;
    private javax.swing.JTextField jtNoMedicos;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
