/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import InterfacesExtras.RemodelarInicio;
import InterfacesExtras.VntAltaaPaciente;
import InterfacesExtras.VntBajarTerNivel;
import InterfacesExtras.VntRemodelarFin;
import InterfacesExtras.VntSubirTerNivel;
import codigo.Bicola;
import codigo.ListaAnt;
import codigo.ManipulaArchivos;
import codigo.MnpHDEP;
import codigo.Multilista;
import codigo.NodoML;
import interfacesConsultas.ConsultaGeneral;

/**
 *
 * @author ErIcK
 */
public class Vntp extends javax.swing.JFrame
{

    /**
     * Creates new form Vntp
     */
    public Vntp()
    {
        initComponents();
        MnpHDEP.mList = (Multilista) codigo.ManipulaArchivos.cargaMultiLista("Dependencias.dat");
        MnpHDEP.listaRef = (ListaAnt) codigo.ManipulaArchivos.cargaListaAnt("HospitaesRemo.dat");
        MnpHDEP.cveArr = (int[]) codigo.ManipulaArchivos.cargaAint("Folios.dat");
        MnpHDEP.bicola = (Bicola<NodoML>) codigo.ManipulaArchivos.cargaBicola("Bicola.dat");

        jToolBar1.setFloatable(false);
        jToolBar2.setFloatable(false);
        jToolBar3.setFloatable(false);
        jToolBar4.setFloatable(false);
        jToolBar5.setFloatable(false);
        jToolBar6.setFloatable(false);
        jToolBar7.setFloatable(false);
        jToolBar8.setFloatable(false);
        jToolBar9.setFloatable(false);
        try
        {
            jcMiniConsulta.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    String opc = jcMiniConsulta.getSelectedItem().toString();
                    switch (opc)
                    {
                        case "Dependencias":
                            jtConsulta.setText(MnpHDEP.mostrarDependencias(true));
                            break;
                        case "Hospitales":
                            jtConsulta.setText(MnpHDEP.mostrarHospitalesCdep(true));
                            break;
                        case "Especialidades":
                            jtConsulta.setText(MnpHDEP.mostrarEspecialidadChdep(true));
                            break;
                        case "Pacientes":
                            jtConsulta.setText(MnpHDEP.mostrarPacienteChdep(true));
                            break;
                        default:
                            jtConsulta.setText("Sin datos");
                    }

                }
            });
        } catch (Exception ex)
        {
            jtConsulta.setText("Sin datos");
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e)
            {
                codigo.ManipulaArchivos.guardaMultilista(MnpHDEP.mList, "Dependencias.dat");
                codigo.ManipulaArchivos.guardaFolio(MnpHDEP.cveArr, "Folios.dat");
                ManipulaArchivos.guardaListaAnt(MnpHDEP.listaRef, "HospitaesRemo.dat");
                ManipulaArchivos.guardaBicola(MnpHDEP.bicola, "Bicola.dat");
                int opcion = javax.swing.JOptionPane.showConfirmDialog(
                        Vntp.this,
                        "¿Deseas guardar y salir?",
                        "Confirmar salida",
                        javax.swing.JOptionPane.YES_NO_OPTION
                );

                if (opcion == javax.swing.JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jToolBar1 = new javax.swing.JToolBar();
        bAlta = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        bBaja = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        bModifica = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        bConsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar5 = new javax.swing.JToolBar();
        btnIremodelar = new javax.swing.JButton();
        jToolBar6 = new javax.swing.JToolBar();
        btnTremodelar = new javax.swing.JButton();
        jToolBar7 = new javax.swing.JToolBar();
        btnSubir3 = new javax.swing.JButton();
        jToolBar8 = new javax.swing.JToolBar();
        btnBajar3 = new javax.swing.JButton();
        jToolBar9 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnAlta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jcMiniConsulta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsulta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        jToolBar1.setRollover(true);

        bAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agg2.png"))); // NOI18N
        bAlta.setToolTipText("Alta");
        bAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlta.setFocusable(false);
        bAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bAlta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bAltaActionPerformed(evt);
            }
        });
        jToolBar1.add(bAlta);

        jToolBar2.setRollover(true);

        bBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ex.png"))); // NOI18N
        bBaja.setToolTipText("Baja");
        bBaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bBaja.setFocusable(false);
        bBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBaja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bBajaActionPerformed(evt);
            }
        });
        jToolBar2.add(bBaja);

        jToolBar3.setRollover(true);

        bModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ordenar.png"))); // NOI18N
        bModifica.setToolTipText("Modificar");
        bModifica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bModifica.setFocusable(false);
        bModifica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bModifica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bModifica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bModificaActionPerformed(evt);
            }
        });
        jToolBar3.add(bModifica);

        jToolBar4.setRollover(true);

        bConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        bConsulta.setToolTipText("Consultar");
        bConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bConsulta.setFocusable(false);
        bConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bConsulta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bConsultaActionPerformed(evt);
            }
        });
        jToolBar4.add(bConsulta);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Alta");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Baja");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Modificar");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Consulta");

        jToolBar5.setRollover(true);

        btnIremodelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remoi.png"))); // NOI18N
        btnIremodelar.setToolTipText("Iniciar remodelación");
        btnIremodelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIremodelar.setFocusable(false);
        btnIremodelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIremodelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIremodelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnIremodelarActionPerformed(evt);
            }
        });
        jToolBar5.add(btnIremodelar);

        jToolBar6.setRollover(true);

        btnTremodelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remot.png"))); // NOI18N
        btnTremodelar.setToolTipText("Terminar Remodelación");
        btnTremodelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTremodelar.setFocusable(false);
        btnTremodelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTremodelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTremodelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTremodelarActionPerformed(evt);
            }
        });
        jToolBar6.add(btnTremodelar);

        jToolBar7.setRollover(true);

        btnSubir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sbn3.png"))); // NOI18N
        btnSubir3.setToolTipText("Subir a nivel 3");
        btnSubir3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubir3.setFocusable(false);
        btnSubir3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubir3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSubir3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSubir3ActionPerformed(evt);
            }
        });
        jToolBar7.add(btnSubir3);

        jToolBar8.setRollover(true);

        btnBajar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bjan3.png"))); // NOI18N
        btnBajar3.setToolTipText("Bajar de nivel 3");
        btnBajar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBajar3.setFocusable(false);
        btnBajar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBajar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBajar3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBajar3ActionPerformed(evt);
            }
        });
        jToolBar8.add(btnBajar3);

        jToolBar9.setRollover(true);
        jToolBar9.add(filler1);

        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boti.png"))); // NOI18N
        btnAlta.setToolTipText("Alta Paciente");
        btnAlta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlta.setFocusable(false);
        btnAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAltaActionPerformed(evt);
            }
        });
        jToolBar9.add(btnAlta);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Iniciar remodelación");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Terminar remodelación");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Subir a tercer nivel");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Bajar de tercer nivel");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Dar alta paciente");

        jSeparator1.setToolTipText("");

        jcMiniConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dependencias", "Hospitales", "Especialidades", "Pacientes" }));
        jcMiniConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jtConsulta.setEditable(false);
        jtConsulta.setColumns(20);
        jtConsulta.setRows(5);
        jScrollPane1.setViewportView(jtConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcMiniConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToolBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9))
                            .addComponent(jToolBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(87, 87, 87))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcMiniConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bBajaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bBajaActionPerformed
    {//GEN-HEADEREND:event_bBajaActionPerformed
        VntMenuBajas v = new VntMenuBajas();
        v.setVisible(true);
    }//GEN-LAST:event_bBajaActionPerformed

    private void bModificaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bModificaActionPerformed
    {//GEN-HEADEREND:event_bModificaActionPerformed
        VntMenuModifica v = new VntMenuModifica();
        v.setVisible(true);
    }//GEN-LAST:event_bModificaActionPerformed

    private void bAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bAltaActionPerformed
    {//GEN-HEADEREND:event_bAltaActionPerformed
        // TODO add your handling code here:
        VntMenuAltas m = new VntMenuAltas();
        m.setVisible(true);

    }//GEN-LAST:event_bAltaActionPerformed

    private void bConsultaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bConsultaActionPerformed
    {//GEN-HEADEREND:event_bConsultaActionPerformed
        VntMenuConsultas c = new VntMenuConsultas();
        c.setVisible(true);
    }//GEN-LAST:event_bConsultaActionPerformed

    private void btnIremodelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnIremodelarActionPerformed
    {//GEN-HEADEREND:event_btnIremodelarActionPerformed
        RemodelarInicio r = new RemodelarInicio();
        r.setVisible(true);
    }//GEN-LAST:event_btnIremodelarActionPerformed

    private void btnSubir3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSubir3ActionPerformed
    {//GEN-HEADEREND:event_btnSubir3ActionPerformed
        VntSubirTerNivel n = new VntSubirTerNivel();
        n.setVisible(true);
    }//GEN-LAST:event_btnSubir3ActionPerformed

    private void btnTremodelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTremodelarActionPerformed
    {//GEN-HEADEREND:event_btnTremodelarActionPerformed
        VntRemodelarFin v = new VntRemodelarFin();
        v.setVisible(true);
    }//GEN-LAST:event_btnTremodelarActionPerformed

    private void btnBajar3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBajar3ActionPerformed
    {//GEN-HEADEREND:event_btnBajar3ActionPerformed
        VntBajarTerNivel v = new VntBajarTerNivel();
        v.setVisible(true);
    }//GEN-LAST:event_btnBajar3ActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAltaActionPerformed
    {//GEN-HEADEREND:event_btnAltaActionPerformed
        VntAltaaPaciente v = new VntAltaaPaciente();
        v.setVisible(true);
    }//GEN-LAST:event_btnAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Vntp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Vntp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Vntp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Vntp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Vntp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlta;
    private javax.swing.JButton bBaja;
    private javax.swing.JButton bConsulta;
    private javax.swing.JButton bModifica;
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBajar3;
    private javax.swing.JButton btnIremodelar;
    private javax.swing.JButton btnSubir3;
    private javax.swing.JButton btnTremodelar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JToolBar jToolBar8;
    private javax.swing.JToolBar jToolBar9;
    private javax.swing.JComboBox<String> jcMiniConsulta;
    private javax.swing.JTextArea jtConsulta;
    // End of variables declaration//GEN-END:variables
}
