/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesExtras;

import cjb.ci.CtrlInterfaz;
import codigo.Hospital;
import codigo.ManipulaArchivos;
import interfacesBajas.*;
import codigo.MnpHDEP;
import static codigo.MnpHDEP.encontrarHospital;
import codigo.NodoML;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristo
 */
public class VntBajarTerNivel extends javax.swing.JFrame
{

    /**
     * Creates new form VntBajaHospital
     */
    public VntBajarTerNivel()
    {
        initComponents();
        try
        {
            jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
            jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesConTercerNivel(jcDependencia.getSelectedItem().toString())));

            jcDependencia.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    String dependenciaSeleccionada = jcDependencia.getSelectedItem().toString();
                    jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(
                            codigo.MnpHDEP.mostrarHospitalesConTercerNivel(dependenciaSeleccionada)
                    ));
                }
            });
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jcDependencia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jcHospital = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bajar de tercer nivel");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Selecciona la dependencia a la que pertenece el hospital que quieres bajar de tercer nivel");

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDependencia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcDependenciaKeyPressed(evt);
            }
        });

        jLabel2.setText("Selecciona el hospital que deseas bajar de nivel");

        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcHospital.setEnabled(false);
        jcHospital.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcHospitalKeyPressed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 145, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(172, 172, 172))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar)
                    .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnAceptar)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed

        if (jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas") || jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados con nivel 3"))
        {
            JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio para poder llevar a cabo esta acción", "Campos invalidos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dependencia = jcDependencia.getSelectedItem().toString();
        String hospital = jcHospital.getSelectedItem().toString();

//        ManipulaArchivos.guardaBicola(MnpHDEP.bicola, "Bicola.dat");
        NodoML<Hospital> aux = MnpHDEP.verificarTemporales(dependencia, hospital);
        NodoML<Hospital> n = encontrarHospital(dependencia, hospital);
        

        if (aux != null)
        {
            hospital = aux.getObj().getNombre();
            MnpHDEP.bajarTercerNivel(dependencia, hospital);
            JOptionPane.showMessageDialog(this, "HOSPITAL EN REMODELACIÓN, CAMBIOS HECHOS EN HOSPITAL TEMPORAL: " + aux.getEtiqueta() + "\n" + "El hospital " + hospital + " fue bajado de tercer nivel con exito", "Bajar de tercer nivel", JOptionPane.INFORMATION_MESSAGE);
        } else
        {
            MnpHDEP.bajarTercerNivel(dependencia, hospital);
            JOptionPane.showMessageDialog(this, "El hospital " + hospital + " fue bajado de tercer nivel con exito", "Bajar de tercer nivel", JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        if (n != null)
        {
            n.getObj().setNivel(2);
        }
        
        CtrlInterfaz.habilita(false, jcHospital, btnAceptar);
        CtrlInterfaz.cambia(jcDependencia);

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesConTercerNivel(jcDependencia.getSelectedItem().toString())));
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jcDependenciaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcDependenciaKeyPressed
    {//GEN-HEADEREND:event_jcDependenciaKeyPressed
        if (evt.getKeyChar() == '\n' && jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas"))
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jcHospital.setEnabled(true);
            jcHospital.requestFocus();
        }
    }//GEN-LAST:event_jcDependenciaKeyPressed

    private void jcHospitalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcHospitalKeyPressed
    {//GEN-HEADEREND:event_jcHospitalKeyPressed
        if (jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados con nivel 3") && evt.getKeyChar() == '\n')
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            btnAceptar.setEnabled(true);
            btnAceptar.requestFocus();
        }
    }//GEN-LAST:event_jcHospitalKeyPressed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VntBajarTerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VntBajarTerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VntBajarTerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VntBajarTerNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VntBajarTerNivel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcDependencia;
    private javax.swing.JComboBox<String> jcHospital;
    // End of variables declaration//GEN-END:variables
}
