/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesModificaciones;

import InterfacesAltas.*;
import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import codigo.Hospital;
import codigo.MnpHDEP;
import codigo.NodoML;
import javax.swing.JOptionPane;

/**
 *
 * @author ErIcK
 */
public class VntModificaHospital extends javax.swing.JFrame
{

    /**
     * Creates new form VntAltaDependencia
     */
    public VntModificaHospital()
    {
        initComponents();
        try
        {
            jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
//        if (jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas"))
//        {
//            CtrlInterfaz.habilita(false, jtNombre, jcHospital, jtDireccion, jtNivel, btnAceptar);
//            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
//        }

            jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(jcDependencia.getSelectedItem().toString())));

//        if (jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados"))
//        {
//            CtrlInterfaz.habilita(false, jtNombre, jtDireccion, jtNivel, btnAceptar);
//            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
//        }
            jcDependencia.addActionListener(new java.awt.event.ActionListener()
            {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    String dependenciaSeleccionada = jcDependencia.getSelectedItem().toString();
                    jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(
                            codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(dependenciaSeleccionada)
                    ));
                }
            });
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcDependencia = new javax.swing.JComboBox<>();
        jcHospital = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtNivel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar hospital");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Ingresa el nombre del hospital:");

        jLabel2.setText("Ingresa la direccion del hospital");

        jtNombre.setEnabled(false);
        jtNombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtNombreKeyTyped(evt);
            }
        });

        jtDireccion.setEnabled(false);
        jtDireccion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtDireccionActionPerformed(evt);
            }
        });
        jtDireccion.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                jtDireccionKeyTyped(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });
        btnAceptar.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                btnAceptarKeyPressed(evt);
            }
        });

        jLabel3.setText("Ingresa el nivel del hospital");

        jLabel4.setText("Selecciona la dependencia a la que pertenece el hospital");

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcDependencia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcDependenciaKeyPressed(evt);
            }
        });

        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcHospital.setEnabled(false);
        jcHospital.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jcHospitalKeyPressed(evt);
            }
        });

        jLabel5.setText("Selecciona el hospital que deseas modificar");

        jtNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jtNivel.setEnabled(false);
        jtNivel.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                jtNivelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 114, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtDireccionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtDireccionActionPerformed
    {//GEN-HEADEREND:event_jtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDireccionActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed

        if (jtNombre.getText().trim().length() == 0 || jtDireccion.getText().length() == 0 || jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas") || jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados"))
        {
            JOptionPane.showMessageDialog(this, "Ningun campo puede estar vacio para poder llevar a cabo esta acción", "Datos invalidos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (MnpHDEP.verificarNoDuplicadosDeHospital(jcDependencia.getSelectedItem().toString(), jtNombre.getText().toLowerCase().trim()) && !jtNombre.getText().equals(jcHospital.getSelectedItem().toString()))
        {

            JOptionPane.showMessageDialog(this, "No puedes ingresar una hospital con el mismo nombre en esta dependencia ", "Dato no valido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String dependencia = jcDependencia.getSelectedItem().toString();
        String hospital = jcHospital.getSelectedItem().toString();
        String nombre = jtNombre.getText().trim();
        String dir = jtDireccion.getText().trim();
        int nivel = Integer.parseInt(jtNivel.getSelectedItem().toString());

        NodoML<Hospital> n = MnpHDEP.encontrarHospital(dependencia, hospital);

//        MnpHDEP.modificarHospital(n, nombre, dir, nivel);
//        n.setEtiqueta(nombre);
//        if (MnpHDEP.verificarRemo(nombre))
//        {
//            MnpHDEP.cambiaNombreRemo(hospital, nombre);
//        }
        NodoML<Hospital> tm = MnpHDEP.verificarTemporales(dependencia, hospital);
        if (tm != null)
        {

            if (nivel == 3 && tm.getObj().getNivel() != 3)
            {

                MnpHDEP.subirTercerNivel(dependencia, tm.getObj().getNombre());

            } else if (nivel != 3 && tm.getObj().getNivel() == 3)
            {
                MnpHDEP.bajarTercerNivel(dependencia, tm.getObj().getNombre());
                tm.getObj().setNivel(nivel);
            }

        } else if (n != null)
        {
            if (nivel == 3 && n.getObj().getNivel() != 3)
            {

                MnpHDEP.subirTercerNivel(dependencia, n.getEtiqueta());

            } else if (nivel != 3 && n.getObj().getNivel() == 3)
            {
                MnpHDEP.bajarTercerNivel(dependencia, n.getEtiqueta());
            }

        }
        if (n != null)
        {
            MnpHDEP.modificarHospital(n, nombre, dir, nivel);
            n.setEtiqueta(nombre);
        }

//        if (MnpHDEP.verificarRemoNodo(dependencia, nombre))
//        {
//            MnpHDEP.cambiaNombreRemo(hospital, nombre);
//        }
        JOptionPane.showMessageDialog(this, "El hospital fue actualizado con el nombre: " + nombre + "\n" + "Direccion: " + dir + "\n" + "Nivel: " + nivel, "Modificar hospital", JOptionPane.INFORMATION_MESSAGE);

        CtrlInterfaz.limpia(jtNombre, jtDireccion, jtNivel);
        CtrlInterfaz.habilita(false, jtDireccion, jtNivel, jtNombre, jcHospital, btnAceptar);
        //validacion
        CtrlInterfaz.cambia(jcDependencia);

        jcDependencia.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarDependenciasStCmbox()));
        jcHospital.setModel(new javax.swing.DefaultComboBoxModel<>(codigo.MnpHDEP.mostrarHospitalesOrigenCmbox(jcDependencia.getSelectedItem().toString())));


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNombreKeyTyped
    {//GEN-HEADEREND:event_jtNombreKeyTyped
        Validaciones.validaAlfanumerico(evt, 25, jtNombre.getText());
    }//GEN-LAST:event_jtNombreKeyTyped

    private void jtDireccionKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtDireccionKeyTyped
    {//GEN-HEADEREND:event_jtDireccionKeyTyped
        Validaciones.validaAlfanumerico(evt, 40, jtDireccion.getText());
    }//GEN-LAST:event_jtDireccionKeyTyped

    private void jcDependenciaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcDependenciaKeyPressed
    {//GEN-HEADEREND:event_jcDependenciaKeyPressed
        if (evt.getKeyChar() == '\n' && jcDependencia.getSelectedItem().toString().equals("Sin dependencias registradas"))
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jcHospital.setEnabled(true);
            jcHospital.requestFocus();
        }
    }//GEN-LAST:event_jcDependenciaKeyPressed

    private void jcHospitalKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcHospitalKeyPressed
    {//GEN-HEADEREND:event_jcHospitalKeyPressed
        if (jcHospital.getSelectedItem().toString().equals("Sin hospitales registrados") && evt.getKeyChar() == '\n')
        {

            JOptionPane.showMessageDialog(this, "Ingresa este dato para pasar a la siguiente accion ", "Sin datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (evt.getKeyChar() == '\n')
        {
            jtNombre.setEnabled(true);
            jtNombre.requestFocus();
        }
    }//GEN-LAST:event_jcHospitalKeyPressed

    private void jtNombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNombreKeyPressed
    {//GEN-HEADEREND:event_jtNombreKeyPressed
        if (evt.getKeyChar() == '\n' && MnpHDEP.verificarNoDuplicadosDeHospital(jcDependencia.getSelectedItem().toString(), jtNombre.getText().toLowerCase().trim()) && !jtNombre.getText().equals(jcHospital.getSelectedItem().toString()))
        {

            JOptionPane.showMessageDialog(this, "No puedes ingresar una hospital con el mismo nombre en esta dependencia ", "Dato no valido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Validaciones.enterCadenaNoVacia(this, evt, jtNombre, jtDireccion);
    }//GEN-LAST:event_jtNombreKeyPressed

    private void jtDireccionKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtDireccionKeyPressed
    {//GEN-HEADEREND:event_jtDireccionKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, jtDireccion, jtNivel);
    }//GEN-LAST:event_jtDireccionKeyPressed

    private void btnAceptarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnAceptarKeyPressed
    {//GEN-HEADEREND:event_btnAceptarKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptarActionPerformed(null);
        }
    }//GEN-LAST:event_btnAceptarKeyPressed

    private void jtNivelKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtNivelKeyPressed
    {//GEN-HEADEREND:event_jtNivelKeyPressed
        if (evt.getKeyChar() == '\n')
        {
            btnAceptar.setEnabled(true);
            btnAceptar.requestFocus();
        }
    }//GEN-LAST:event_jtNivelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VntModificaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VntModificaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VntModificaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VntModificaHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VntModificaHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcDependencia;
    private javax.swing.JComboBox<String> jcHospital;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JComboBox<String> jtNivel;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
